### ISSUE TITLE
venv

### ISSUE THREAD

**Issue by robertu** [Jakubmus/ToDoApp#1]
1. Katalog `venv` powinien być poza repo.
2. Środowisko uruchomieniowe (tu: `venv`) nigdy nie powinno być wersjonowane.
3. Kiedy korzystasz z `Dockera` nie potrzebujesz `venv`.

**Comment by Jakubmus** [comment]
Przepraszam ten hasztag zosta dodany przypadkiem nie mialem pojecia, ze tak mozna sie odwolac do problemu

**Comment by robertu** [comment]
![err](https://user-images.githubusercontent.com/1024969/204525932-36c2d05f-75aa-4c59-b6bb-112eea21dac4.png)
