### ISSUE TITLE
README

### ISSUE THREAD

**Issue by GeFeC** [Jakubmus/ToDoApp#4]
Popraw troche to README bo zle wyglada. Mozesz szybko stworzyc naglowek za pomoca dwoch hashtagow, np:
'## Requirements' (Wiekszy naglowek za pomoca pojedynczego hashtagu). Aby przejsc do nowej linii mozesz skorzystac ze zwyklego tagu br, tak jak w HTMLu

**Comment by GeFeC** [comment]
Przy okazji ucielo Ci troche tekstu. Generalnie polecenia, ktore trzeba wpisac w konsoli proponuje wpisywac pomiedzy potrojne backticki (`), np. \```docker build\```

**Comment by Jakubmus** [comment]
Dzieki mordo

**Comment by GeFeC** [comment]
Spoczko

**Comment by Jakubmus** [comment]
Juz powinno byc wszystko git zerknij
