### ISSUE TITLE
Problem ze zbudowaniem aplikacji

### ISSUE THREAD

**Issue by GeFeC** [Jakubmus/ToDoApp#5]
Przy probie stworzenia dockerowego obrazu wyskakuje blad:
ERROR: Could not find a version that satisfies the requirement Flask-SQLAlchem==3.0.2 (from versions: none)
ERROR: No matching distribution found for Flask-SQLAlchem==3.0.2

**Comment by Jakubmus** [comment]
Literowe walnałem XD
