### ISSUE TITLE
Problem loading page

### ISSUE THREAD

**Issue by GeFeC** [Jakubmus/ToDoApp#6]
po uruchomieniu kontenera, strona nie laduje sie. Prawdopodobnie w Dockerfile brakuje tego:
ENV FLASK_RUN_HOST=0.0.0.0

**Comment by Jakubmus** [comment]
Zrobione

**Comment by GeFeC** [comment]
Nadal nie dziala

**Comment by Jakubmus** [comment]
A co ci tak dokladnie wysyakuje pokaz

**Comment by GeFeC** [comment]
strona sie nie laduje w przegladarce. Kontener startuje bez bledow, ale przegladarka nie widzi strony. Cos jest nie tak z Dockerfile

**Comment by Jakubmus** [comment]
dobra juz sie robi

**Comment by Jakubmus** [comment]
Ok juz wszystko dziala

**Comment by GeFeC** [comment]
Good :>
