### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by GeFeC** [Jakubmus/ToDoApp#8]
W requirements w README zostaw tylko docker-engine, a reszte usun. Wszystkie zaleznosci takie jak 'python', 'pip' i wszystkie moduly sa instalowane w kontenerze Dockera, ktory wie o tym, ktore zaleznosci trzeba zainstalowac dzieki plikowi Dockerfile i requirements.txt
Sekcja requirements jest moim zdaniem mylaca.

**Comment by Jakubmus** [comment]
Zrobione
